

let allMusic = [
    {
        name: "Aa Chal Ke Tujhe",
        artist: "Kishore Kumar",
        song_duration: "04:39",
        img: "Aa Chal Ke Tujhe",
        src: "Aa Chal Ke Tujhe",
    },
    {
        name: "Aa Jaane-Jaan",
        artist: "Lata Mangeshkar",
        song_duration: "06:27",
        img: "Aa Jaane-Jaan",
        src: "Aa Jaane-Jaan",
    },
    {
        name: "Aage Bhi Jane Na Tu",
        artist: "Asha Bhosle",
        song_duration: "07:28",
        img: "Aage Bhi Jane Na Tu",
        src: "Aage Bhi Jane Na Tu",
    },
    {
        name: "Aaiye Meharban",
        artist: "Asha Bhosle",
        song_duration: "04:12",
        img: "Aaiye Meharban",
        src: "Aaiye Meharban",
    },
    {
        name: "Aaj Kahin Na Ja",
        artist: "Lata Mangeshkar & Kishore Kumar & R. D. Burman",
        song_duration: "04:30",
        img: "Aaj Kahin Na Ja",
        src: "Aaj Kahin Na Ja",
    },
    {
        name: "Aaj Ki Raat Koi Aane Ko Hai",
        artist: "Asha Bhosle & R. D. Burman",
        song_duration: "06:19",
        img: "Aaj Ki Raat Koi Aane Ko Hai",
        src: "Aaj Ki Raat Koi Aane Ko Hai",
    },
    {
        name: "Aaj Madhosh Hua Jaye Re",
        artist: "Kishore Kumar & Lata Mangeshkar",
        song_duration: "04:54",
        img: "Aaj Madhosh Hua Jaye Re",
        src: "Aaj Madhosh Hua Jaye Re",
    },
    {
        name: "Aaj Mausam Bada Beimaan Hai",
        artist: "Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "06:14",
        img: "Aaj Mausam Bada Beimaan Hai",
        src: "Aaj Mausam Bada Beimaan Hai",
    },
    {
        name: "Aaj Phir Jeene Ki Tamanna Hai",
        artist: "Lata Mangeshkar & S. D. Burman",
        song_duration: "03:58",
        img: "Aaj Phir Jeene Ki Tamanna Hai",
        src: "Aaj Phir Jeene Ki Tamanna Hai",
    },
    {
        name: "Aaj Rapat Jaayen To",
        artist: "Kishore Kumar & Asha Bhosle",
        song_duration: "06:48",
        img: "Aaj Rapat Jaayen To",
        src: "Aaj Rapat Jaayen To",
    },
    {
        name: "Aaj Unse Pehli Mulaqat Hogi",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "05:46",
        img: "Aaj Unse Pehli Mulaqat Hogi",
        src: "Aaj Unse Pehli Mulaqat Hogi",
    },
    {
        name: "Aaja Aaja Main Hoon Pyar Tera",
        artist: "Asha Bhosle & Mohammed Rafi & R. D. Burman",
        song_duration: "06:41",
        img: "Aaja Aaja Main Hoon Pyar Tera",
        src: "Aaja Aaja Main Hoon Pyar Tera",
    },
    {
        name: "Aaja Piya Tohe Pyar Doon",
        artist: "Lata Mangeshkar & R. D. Burman",
        song_duration: "04:11",
        img: "Aaja Piya Tohe Pyar Doon",
        src: "Aaja Piya Tohe Pyar Doon",
    },
    {
        name: "Aaja Sanam Madhur Chandni Men",
        artist: "Lata Mangeshkar & Manna Dey",
        song_duration: "04:25",
        img: "Aaja Sanam Madhur Chandni Men",
        src: "Aaja Sanam Madhur Chandni Men",
    },
    {
        name: "Aajkal Paon Zaamin Par Nahin Padte",
        artist: "Lata Mangeshkar & R. D. Burman",
        song_duration: "05:29",
        img: "Aajkal Paon Zaamin Par Nahin Padte",
        src: "Aajkal Paon Zaamin Par Nahin Padte",
    },
    {
        name: "Aajkal Tere Mere Pyar Ke Charche",
        artist: "Suman Kalyanpur & Mohammed Rafi",
        song_duration: "05:09",
        img: "Aajkal Tere Mere Pyar Ke Charche",
        src: "Aajkal Tere Mere Pyar Ke Charche",
    },
    {
        name: "Aane Se Uske Aaye Bahar",
        artist: "Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "04:07",
        img: "Aane Se Uske Aaye Bahar",
        src: "Aane Se Uske Aaye Bahar",
    },
    {
        name: "Aanewala Pal Janewala Hai",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:39",
        img: "Aanewala Pal Janewala Hai",
        src: "Aanewala Pal Janewala Hai",
    },
    {
        name: "Aao Huzoor Tumko",
        artist: "Asha Bhosle",
        song_duration: "05:52",
        img: "Aao Huzoor Tumko",
        src: "Aao Huzoor Tumko",
    },
    {
        name: "Aao Na Gale Lag Jao Na",
        artist: "Asha Bhosle & R. D. Burman",
        song_duration: "04:56",
        img: "Aao Na Gale Lag Jao Na",
        src: "Aao Na Gale Lag Jao Na",
    },
    {
        name: "Aap Ke Haseen Rukh Pe",
        artist: "Mohammed Rafi",
        song_duration: "05:38",
        img: "Aap Ke Haseen Rukh Pe",
        src: "Aap Ke Haseen Rukh Pe",
    },
    {
        name: "Aap Ki Ankhon Mein Kuch",
        artist: "Kishore Kumar & Lata Mangeshkar & R. D. Burman",
        song_duration: "04:09",
        img: "Aap Ki Ankhon Mein Kuch",
        src: "Aap Ki Ankhon Mein Kuch",
    },
    {
        name: "Aap Ki Nazron Ne Samjha",
        artist: "Lata Mangeshkar",
        song_duration: "03:54",
        img: "Aap Ki Nazron Ne Samjha",
        src: "Aap Ki Nazron Ne Samjha",
    },
    {
        name: "Aasman Ke Neeche",
        artist: "Lata Mangeshkar & Kishore Kumar & S. D. Burman",
        song_duration: "03:55",
        img: "Aasman Ke Neeche",
        src: "Aasman Ke Neeche",
    },
    {
        name: "Aate Jaate Hanste Gaate",
        artist: "Lata Mangeshkar & S. P. Balasubrahmanyam",
        song_duration: "03:24",
        img: "Aate Jaate Hanste Gaate",
        src: "Aate Jaate Hanste Gaate",
    },
    {
        name: "Aate Jate Khoobsurat Awara",
        artist: "Kishore Kumar & Laxmikant–Pyarelal",
        song_duration: "05:53",
        img: "Aate Jate Khoobsurat Awara",
        src: "Aate Jate Khoobsurat Awara",
    },
    {
        name: "Aaye Tum Yaad Mujhe",
        artist: "Kishore Kumar & S. D. Burman",
        song_duration: "04:41",
        img: "Aaye Tum Yaad Mujhe",
        src: "Aaye Tum Yaad Mujhe",
    },
    {
        name: "Ab Ke Sajan Sawan Mein",
        artist: "Lata Mangeshkar & S. D. Burman",
        song_duration: "04:41",
        img: "Ab Ke Sajan Sawan Mein",
        src: "Ab Ke Sajan Sawan Mein",
    },
    {
        name: "Ab To Hai Tumse Har Khushi Apni",
        artist: "Lata Mangeshkar & S. D. Burman",
        song_duration: "04:45",
        img: "Ab To Hai Tumse Har Khushi Apni",
        src: "Ab To Hai Tumse Har Khushi Apni",
    },
    {
        name: "Abhi Na Jao Chhod Kar",
        artist: "Asha Bhosle & Mohammed Rafi",
        song_duration: "04:18",
        img: "Abhi Na Jao Chhod Kar",
        src: "Abhi Na Jao Chhod Kar",
    },
    {
        name: "Achha Ji Main Haari Chalo",
        artist: "Asha Bhosle & Mohammed Rafi & S. D. Burman",
        song_duration: "03:27",
        img: "Achha Ji Main Haari Chalo",
        src: "Achha Ji Main Haari Chalo",
    },
    {
        name: "Achha To Hum Chalte Hain",
        artist: "Lata Mangeshkar & Kishore Kumar & Laxmikant–Pyarelal",
        song_duration: "04:58",
        img: "Achha To Hum Chalte Hain",
        src: "Achha To Hum Chalte Hain",
    },
    {
        name: "Ae Ri Pawan",
        artist: "Lata Mangeshkar",
        song_duration: "05:29",
        img: "Ae Ri Pawan",
        src: "Ae Ri Pawan",
    },
    {
        name: "Aese To Na Dekho",
        artist: "Mohammed Rafi & S. D. Burman",
        song_duration: "03:50",
        img: "Aese To Na Dekho",
        src: "Aese To Na Dekho",
    },
    {
        name: "Ajib Dastan Hai Yeh",
        artist: "Lata Mangeshkar",
        song_duration: "05:15",
        img: "Ajib Dastan Hai Yeh",
        src: "Ajib Dastan Hai Yeh",
    },
    {
        name: "Akele Akele Kahan Ja Rahe Ho",
        artist: "Mohammed Rafi",
        song_duration: "04:45",
        img: "Akele Akele Kahan Ja Rahe Ho",
        src: "Akele Akele Kahan Ja Rahe Ho",
    },
    {
        name: "An Evening In Paris",
        artist: "Mohammed Rafi",
        song_duration: "05:18",
        img: "An Evening In Paris",
        src: "An Evening In Paris",
    },
    {
        name: "Ankhiyon Ko Rahne De",
        artist: "Lata Mangeshkar & Laxmikant–Pyarelal",
        song_duration: "05:05",
        img: "Ankhiyon Ko Rahne De",
        src: "Ankhiyon Ko Rahne De",
    },
    {
        name: "Ankhon Hi Ankhon Mein",
        artist: "Geeta Dutt & Mohammed Rafi",
        song_duration: "03:57",
        img: "Ankhon Hi Ankhon Mein",
        src: "Ankhon Hi Ankhon Mein",
    },
    {
        name: "Ankhon Mein Kajal Hai",
        artist: "Lata Mangeshkar & Kishore Kumar",
        song_duration: "03:52",
        img: "Ankhon Mein Kajal Hai",
        src: "Ankhon Mein Kajal Hai",
    },
    {
        name: "Ankhon Men Humne Aapke Sapne",
        artist: "Lata Mangeshkar & Kishore Kumar",
        song_duration: "04:38",
        img: "Ankhon Men Humne Aapke Sapne",
        src: "Ankhon Men Humne Aapke Sapne",
    },
    {
        name: "Apni To Jaise Taise",
        artist: "Kishore Kumar & Kalyanji-Anandji",
        song_duration: "08:02",
        img: "Apni To Jaise Taise",
        src: "Apni To Jaise Taise",
    },
    {
        name: "Are Diwano Mujhe Pehchano Dialogue",
        artist: "Kishore Kumar & Kalyanji-Anandji",
        song_duration: "04:49",
        img: "Are Diwano Mujhe Pehchano Dialogue",
        src: "Are Diwano Mujhe Pehchano Dialogue",
    },
    {
        name: "Are Jane Kaise Kab Kahan Iqrar",
        artist: "Kishore Kumar & Lata Mangeshkar & R. D. Burman",
        song_duration: "05:39",
        img: "Are Jane Kaise Kab Kahan Iqrar",
        src: "Are Jane Kaise Kab Kahan Iqrar",
    },
    {
        name: "Are Yaar Meri Tum Bhi Ho Ghazab",
        artist: "Kishore Kumar & Asha Bhosle & S. D. Burman",
        song_duration: "05:19",
        img: "Are Yaar Meri Tum Bhi Ho Ghazab",
        src: "Are Yaar Meri Tum Bhi Ho Ghazab",
    },
    {
        name: "Awara Hoon",
        artist: "Mukesh",
        song_duration: "03:03",
        img: "Awara Hoon",
        src: "Awara Hoon",
    },
    {
        name: "Aye-Dil-E-Nadan",
        artist: "Lata Mangeshkar",
        song_duration: "05:39",
        img: "Aye-Dil-E-Nadan",
        src: "Aye-Dil-E-Nadan",
    },
    {
        name: "Baar Baar Dekho Hazar Baar Dekho",
        artist: "Mohammed Rafi",
        song_duration: "04:51",
        img: "Baar Baar Dekho Hazar Baar Dekho",
        src: "Baar Baar Dekho Hazar Baar Dekho",
    },
    {
        name: "Bachna Ae Hasinon Lo Main Aa Gaya",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "06:24",
        img: "Bachna Ae Hasinon Lo Main Aa Gaya",
        src: "Bachna Ae Hasinon Lo Main Aa Gaya",
    },
    {
        name: "Badan Pe Sitare Lapete Huye",
        artist: "Mohammed Rafi",
        song_duration: "04:48",
        img: "Badan Pe Sitare Lapete Huye",
        src: "Badan Pe Sitare Lapete Huye",
    },
    {
        name: "Badi Sooni Sooni Hai Zindagi",
        artist: "Kishore Kumar & S. D. Burman",
        song_duration: "03:29",
        img: "Badi Sooni Sooni Hai Zindagi",
        src: "Badi Sooni Sooni Hai Zindagi",
    },
    {
        name: "Baharo Phool Barsao",
        artist: "Mohammed Rafi",
        song_duration: "04:27",
        img: "Baharo Phool Barsao",
        src: "Baharo Phool Barsao",
    },
    {
        name: "Bahon Mein Chale Aao",
        artist: "Lata Mangeshkar & R. D. Burman",
        song_duration: "04:01",
        img: "Bahon Mein Chale Aao",
        src: "Bahon Mein Chale Aao",
    },
    
    {
        name: "Bangle Ke Peechhe",
        artist: "Lata Mangeshkar & R. D. Burman",
        song_duration: "05:39",
        img: "Bangle Ke Peechhe",
        src: "Bangle Ke Peechhe",
    },
    {
        name: "Beeti Na Bitai Raina",
        artist: "Lata Mangeshkar & Bhupinder Singh & R. D. Burman",
        song_duration: "03:13",
        img: "Beeti Na Bitai Raina",
        src: "Beeti Na Bitai Raina",
    },
    {
        name: "Bekhudi Mein Sanam",
        artist: "Lata Mangeshkar & Mohammed Rafi & Kalyanji-Anandji",
        song_duration: "04:20",
        img: "Bekhudi Mein Sanam",
        src: "Bekhudi Mein Sanam",
    },
    {
        name: "Bhanware Ki Gunjan",
        artist: "Kishore Kumar",
        song_duration: "04:25",
        img: "Bhanware Ki Gunjan",
        src: "Bhanware Ki Gunjan",
    },
    {
        name: "Bheegi Bheegi Raaton Mein",
        artist: "Lata Mangeshkar & Kishore Kumar & R. D. Burman",
        song_duration: "03:53",
        img: "Bheegi Bheegi Raaton Mein",
        src: "Bheegi Bheegi Raaton Mein",
    },
    {
        name: "Chabi Kho Jayi - Hum Tum Ek Kamre Mein",
        artist: "Lata Mangeshkar & Shailendra Singh & Laxmikant–Pyarelal",
        song_duration: "04:42",
        img: "Chabi Kho Jayi - Hum Tum Ek Kamre Mein",
        src: "Chabi Kho Jayi - Hum Tum Ek Kamre Mein",
    },
    {
        name: "Chadhti Jawani Meri Chaal Mastani",
        artist: "Lata Mangeshkar & Mohammed Rafi & R. D. Burman",
        song_duration: "07:17",
        img: "Chadhti Jawani Meri Chaal Mastani",
        src: "Chadhti Jawani Meri Chaal Mastani",
    },
    
    {
        name: "Chahiye Thoda Pyar",
        artist: "Kishore Kumar",
        song_duration: "05:25",
        img: "Chahiye Thoda Pyar",
        src: "Chahiye Thoda Pyar",
    },
    {
        name: "Chahoonga Main Tujhe",
        artist: "Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "04:54",
        img: "Chahoonga Main Tujhe",
        src: "Chahoonga Main Tujhe",
    },
    {
        name: "Chal Chal Chal Mere Saathi",
        artist: "Kishore Kumar & Laxmikant–Pyarelal",
        song_duration: "05:58",
        img: "Chal Chal Chal Mere Saathi",
        src: "Chal Chal Chal Mere Saathi",
    },
    {
        name: "Chal Kahin Door Nikal Jayen",
        artist: "Lata Mangeshkar & Kishore Kumar & Mohammed Rafi",
        song_duration: "06:36",
        img: "Chal Kahin Door Nikal Jayen",
        src: "Chal Kahin Door Nikal Jayen",
    },
    {
        name: "Chala Jata Hoon",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:29",
        img: "Chala Jata Hoon",
        src: "Chala Jata Hoon",
    },
    {
        name: "Chalte Chalte Yun Hi Koi",
        artist: "Lata Mangeshkar",
        song_duration: "05:53",
        img: "Chalte Chalte Yun Hi Koi",
        src: "Chalte Chalte Yun Hi Koi",
    },
    {
        name: "Chand Mera Dil Chandni Ho Tum",
        artist: "Mohammed Rafi & R. D. Burman",
        song_duration: "02:57",
        img: "Chand Mera Dil Chandni Ho Tum",
        src: "Chand Mera Dil Chandni Ho Tum",
    },
    {
        name: "Chand Si Mehbooba Ho Meri",
        artist: "Mukesh & Kalyanji-Anandji",
        song_duration: "03:57",
        img: "Chand Si Mehbooba Ho Meri",
        src: "Chand Si Mehbooba Ho Meri",
    },
    {
        name: "Chaudhvin Ka Chand Ho",
        artist: "Mohammed Rafi",
        song_duration: "03:43",
        img: "Chaudhvin Ka Chand Ho",
        src: "Chaudhvin Ka Chand Ho",
    },
    {
        name: "Chhalka Yeh Jaam",
        artist: "Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "04:46",
        img: "Chhalka Yeh Jaam",
        src: "Chhalka Yeh Jaam",
    },
    {
        name: "Chhod Do Aanchal Zamana Kya Kahega",
        artist: "Kishore Kumar & Asha Bhosle & S. D. Burman",
        song_duration: "04:10",
        img: "Chhod Do Aanchal Zamana Kya Kahega",
        src: "Chhod Do Aanchal Zamana Kya Kahega",
    },
    {
        name: "Chhoti Si Kahani Se",
        artist: "Asha Bhosle & R. D. Burman",
        song_duration: "07:14",
        img: "Chhoti Si Kahani Se",
        src: "Chhoti Si Kahani Se",
    },
    {
        name: "Chingari Koi Bhadke",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "05:19",
        img: "Chingari Koi Bhadke",
        src: "Chingari Koi Bhadke",
    },
    {
        name: "Chithi Na Koi Sandesh-Jagjit Singh",
        artist: "Jagjit Singh",
        song_duration: "06:37",
        img: "Chithi Na Koi Sandesh-Jagjit Singh",
        src: "Chithi Na Koi Sandesh-Jagjit Singh",
    },
    {
        name: "Chup Gaye Sare Nazare",
        artist: "Lata Mangeshkar & Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "05:29",
        img: "Chup Gaye Sare Nazare",
        src: "Chup Gaye Sare Nazare",
    },
    {
        name: "Chura Liya Hai Tumne Jo Dil Ko",
        artist: "Asha Bhosle & Mohammed Rafi & R. D. Burman",
        song_duration: "04:47",
        img: "Chura Liya Hai Tumne Jo Dil Ko",
        src: "Chura Liya Hai Tumne Jo Dil Ko",
    },
    {
        name: "Dard-E-Dil Dard-E-Jigar",
        artist: "Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "06:57",
        img: "Dard-E-Dil Dard-E-Jigar",
        src: "Dard-E-Dil Dard-E-Jigar",
    },
    {
        name: "De De Pyar De",
        artist: "Kishore Kumar",
        song_duration: "05:47",
        img: "De De Pyar De",
        src: "De De Pyar De",
    },
    
    {
        name: "Deewana Mujhsa Nahin",
        artist: "Mohammed Rafi & R. D. Burman",
        song_duration: "03:22",
        img: "Deewana Mujhsa Nahin",
        src: "Deewana Mujhsa Nahin",
    },
    {
        name: "Dekha Ek Khwab",
        artist: "Lata Mangeshkar & Kishore Kumar",
        song_duration: "05:20",
        img: "Dekha Ek Khwab",
        src: "Dekha Ek Khwab",
    },
    {
        name: "Dekha Na Haye Re",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:12",
        img: "Dekha Na Haye Re",
        src: "Dekha Na Haye Re",
    },
    {
        name: "Dekho Maine Dekha Hai Ek Sapna",
        artist: "Lata Mangeshkar & Amit Kumar & R. D. Burman",
        song_duration: "04:17",
        img: "Dekho Maine Dekha Hai Ek Sapna",
        src: "Dekho Maine Dekha Hai Ek Sapna",
    },
    
    {
        name: "Der Na Ho Jaye Kahin",
        artist: "Lata Mangeshkar & Suresh Wadkar & Mohammad Sayeed & Farid Sabri & Satish",
        song_duration: "08:21",
        img: "Der Na Ho Jaye Kahin",
        src: "Der Na Ho Jaye Kahin",
    },
    {
        name: "Dhal Gaya Din Ho Gayi Sham",
        artist: "Asha Bhosle & Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "04:53",
        img: "Dhal Gaya Din Ho Gayi Sham",
        src: "Dhal Gaya Din Ho Gayi Sham",
    },
    {
        name: "Didi Tera Devar Deewana",
        artist: "Lata Mangeshkar & S. P. Balasubrahmanyam",
        song_duration: "08:05",
        img: "Didi Tera Devar Deewana",
        src: "Didi Tera Devar Deewana",
    },
    {
        name: "Dikhai Diye Yun",
        artist: "Lata Mangeshkar",
        song_duration: "04:20",
        img: "Dikhai Diye Yun",
        src: "Dikhai Diye Yun",
    },
    {
        name: "Dil Aesa Kisine Mera Toda",
        artist: "Kishore Kumar",
        song_duration: "04:59",
        img: "Dil Aesa Kisine Mera Toda",
        src: "Dil Aesa Kisine Mera Toda",
    },
    {
        name: "Dil Cheez Kya Hai",
        artist: "Asha Bhosle",
        song_duration: "06:10",
        img: "Dil Cheez Kya Hai",
        src: "Dil Cheez Kya Hai",
    },
    {
        name: "Dil Deewana",
        artist: "Lata Mangeshkar",
        song_duration: "05:54",
        img: "Dil Deewana",
        src: "Dil Deewana",
    },
    {
        name: "Dil Dhundta Hai",
        artist: "Bhupinder Singh & Lata Mangeshkar",
        song_duration: "08:18",
        img: "Dil Dhundta Hai",
        src: "Dil Dhundta Hai",
    },
    {
        name: "Dil Jo Na Keh Saka",
        artist: "Mohammed Rafi",
        song_duration: "04:22",
        img: "Dil Jo Na Keh Saka",
        src: "Dil Jo Na Keh Saka",
    },
    {
        name: "Dil Ka Bhanwar Kare Pukar",
        artist: "Mohammed Rafi & S. D. Burman",
        song_duration: "03:19",
        img: "Dil Ka Bhanwar Kare Pukar",
        src: "Dil Ka Bhanwar Kare Pukar",
    },
    {
        name: "Dil Ke Jharokhe Mein",
        artist: "Mohammed Rafi",
        song_duration: "06:39",
        img: "Dil Ke Jharokhe Mein",
        src: "Dil Ke Jharokhe Mein",
    },
    {
        name: "Dil Ki Girah Khol Do",
        artist: "Lata Mangeshkar & Manna Dey",
        song_duration: "04:33",
        img: "Dil Ki Girah Khol Do",
        src: "Dil Ki Girah Khol Do",
    },
    {
        name: "Dil Ki Nazar Se",
        artist: "Lata Mangeshkar & Mukesh",
        song_duration: "04:40",
        img: "Dil Ki Nazar Se",
        src: "Dil Ki Nazar Se",
    },
    {
        name: "Dil Pukare Aare Aare",
        artist: "Lata Mangeshkar & Mohammed Rafi & S. D. Burman",
        song_duration: "05:18",
        img: "Dil Pukare Aare Aare",
        src: "Dil Pukare Aare Aare",
    },
    {
        name: "Dil Tadap Tadap Ke Kah Raha",
        artist: "Mukesh & Lata Mangeshkar & Salil Chowdhury",
        song_duration: "03:27",
        img: "Dil Tadap Tadap Ke Kah Raha",
        src: "Dil Tadap Tadap Ke Kah Raha",
    },
    {
        name: "Dil To Hai Dil",
        artist: "Lata Mangeshkar & Kalyanji-Anandji",
        song_duration: "04:10",
        img: "Dil To Hai Dil",
        src: "Dil To Hai Dil",
    },
    {
        name: "Dil Wil Pyar Wyar",
        artist: "Lata Mangeshkar & Laxmikant–Pyarelal",
        song_duration: "05:09",
        img: "Dil Wil Pyar Wyar",
        src: "Dil Wil Pyar Wyar",
    },
    {
        name: "Din Dhal Jaye Haye",
        artist: "Mohammed Rafi & S. D. Burman",
        song_duration: "04:53",
        img: "Din Dhal Jaye Haye",
        src: "Din Dhal Jaye Haye",
    },
    {
        name: "Diwana Hua Badal",
        artist: "Asha Bhosle & Mohammed Rafi",
        song_duration: "05:56",
        img: "Diwana Hua Badal",
        src: "Diwana Hua Badal",
    },
    {
        name: "Diwana Leke Aaya Hai",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:39",
        img: "Diwana Leke Aaya Hai",
        src: "Diwana Leke Aaya Hai",
    },
    {
        name: "Diye Jalte Hai Phool Khilte Hai",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "03:28",
        img: "Diye Jalte Hai Phool Khilte Hai",
        src: "Diye Jalte Hai Phool Khilte Hai",
    },
    {
        name: "Do Lafzon Ki Hai Dil Ki Kahani",
        artist: "Amitabh Bachchan & Asha Bhosle & Sharad Kumar & R. D. Burman",
        song_duration: "06:22",
        img: "Do Lafzon Ki Hai Dil Ki Kahani",
        src: "Do Lafzon Ki Hai Dil Ki Kahani",
    },
    {
        name: "Dream Girl",
        artist: "Kishore Kumar & Laxmikant–Pyarelal",
        song_duration: "05:57",
        img: "Dream Girl",
        src: "Dream Girl",
    },
    {
        name: "Dum Dum Diga Diga",
        artist: "Mukesh & Kalyanji-Anandji",
        song_duration: "03:21",
        img: "Dum Dum Diga Diga",
        src: "Dum Dum Diga Diga",
    },
    {
        name: "Dum Maro Dum Mit Jaye Gham",
        artist: "Asha Bhosle & R. D. Burman",
        song_duration: "02:36",
        img: "Dum Maro Dum Mit Jaye Gham",
        src: "Dum Maro Dum Mit Jaye Gham",
    },
    {
        name: "Duniya Mein Logon Ko",
        artist: "Asha Bhosle & R. D. Burman",
        song_duration: "05:54",
        img: "Duniya Mein Logon Ko",
        src: "Duniya Mein Logon Ko",
    },
    {
        name: "Eena Meena Deeka - Kishore Kumar",
        artist: "Kishore Kumar",
        song_duration: "03:29",
        img: "Eena Meena Deeka - Kishore Kumar",
        src: "Eena Meena Deeka - Kishore Kumar",
    },
    {
        name: "Ehsan Tera Hoga Mujh Par",
        artist: "Mohammed Rafi",
        song_duration: "03:26",
        img: "Ehsan Tera Hoga Mujh Par",
        src: "Ehsan Tera Hoga Mujh Par",
    },
    {
        name: "Ek Ajnabee Haseena Se",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:26",
        img: "Ek Ajnabee Haseena Se",
        src: "Ek Ajnabee Haseena Se",
    },
    {
        name: "Ek Baat Kahoon Gar Mano Tum",
        artist: "Lata Mangeshkar & R. D. Burman",
        song_duration: "03:59",
        img: "Ek Baat Kahoon Gar Mano Tum",
        src: "Ek Baat Kahoon Gar Mano Tum",
    },
    {
        name: "Ek Din Bik Jayega Mati Ke Mol - Happy",
        artist: "Mukesh & R. D. Burman",
        song_duration: "05:38",
        img: "Ek Din Bik Jayega Mati Ke Mol - Happy",
        src: "Ek Din Bik Jayega Mati Ke Mol - Happy",
    },
    {
        name: "Ek Hasina Thi Ek Diwana Tha",
        artist: "Kishore Kumar & Asha Bhosle & Rishi Kapoor & Laxmikant–Pyarelal",
        song_duration: "07:53",
        img: "Ek Hasina Thi Ek Diwana Tha",
        src: "Ek Hasina Thi Ek Diwana Tha",
    },
    {
        name: "Ek Ladki Bheegi Bhagi Si",
        artist: "Kishore Kumar & S. D. Burman",
        song_duration: "04:04",
        img: "Ek Ladki Bheegi Bhagi Si",
        src: "Ek Ladki Bheegi Bhagi Si",
    },
    {
        name: "Ek Main Aur Ek Tu",
        artist: "Asha Bhosle & Kishore Kumar & R. D. Burman",
        song_duration: "04:50",
        img: "Ek Main Aur Ek Tu",
        src: "Ek Main Aur Ek Tu",
    },
    {
        name: "Ek Pardesi Mera Dil Le Gaya",
        artist: "Mohammed Rafi & Asha Bhosle",
        song_duration: "04:00",
        img: "Ek Pardesi Mera Dil Le Gaya",
        src: "Ek Pardesi Mera Dil Le Gaya",
    },
    {
        name: "Ek Pyar Ka Naghma Hai - Happy",
        artist: "Lata Mangeshkar & Mukesh & Laxmikant–Pyarelal",
        song_duration: "06:06",
        img: "Ek Pyar Ka Naghma Hai - Happy",
        src: "Ek Pyar Ka Naghma Hai - Happy",
    },
    {
        name: "Ek Roz Main Tadapkar",
        artist: "Kishore Kumar",
        song_duration: "06:04",
        img: "Ek Roz Main Tadapkar",
        src: "Ek Roz Main Tadapkar",
    },
    {
        name: "Gaata Rahe Mera Dil",
        artist: "Lata Mangeshkar & Kishore Kumar & S. D. Burman",
        song_duration: "04:52",
        img: "Gaata Rahe Mera Dil",
        src: "Gaata Rahe Mera Dil",
    },
    {
        name: "Ghunghroo Ki Tarah Bajta Hi Raha",
        artist: "Kishore Kumar",
        song_duration: "04:45",
        img: "Ghunghroo Ki Tarah Bajta Hi Raha",
        src: "Ghunghroo Ki Tarah Bajta Hi Raha",
    },
    {
        name: "Goom Hai Kisi Ke Pyar Mein",
        artist: "Kishore Kumar & Lata Mangeshkar & R. D. Burman",
        song_duration: "04:15",
        img: "Goom Hai Kisi Ke Pyar Mein",
        src: "Goom Hai Kisi Ke Pyar Mein",
    },
    {
        name: "Gumnaam Hai Koi Badnaam Hai Koi",
        artist: "Lata Mangeshkar",
        song_duration: "05:19",
        img: "Gumnaam Hai Koi Badnaam Hai Koi",
        src: "Gumnaam Hai Koi Badnaam Hai Koi",
    },
    {
        name: "Gun Guna Rahe Hai Bhanvare",
        artist: "Asha Bhosle & Mohammed Rafi & S. D. Burman",
        song_duration: "03:53",
        img: "Gun Guna Rahe Hai Bhanvare",
        src: "Gun Guna Rahe Hai Bhanvare",
    },
    {
        name: "Haal Kaisa Hai Janab Ka",
        artist: "Asha Bhosle & Kishore Kumar & S. D. Burman",
        song_duration: "04:24",
        img: "Haal Kaisa Hai Janab Ka",
        src: "Haal Kaisa Hai Janab Ka",
    },
    {
        name: "Haan Pahli Bar",
        artist: "Kishore Kumar",
        song_duration: "05:47",
        img: "Haan Pahli Bar",
        src: "Haan Pahli Bar",
    },
    {
        name: "Ham Hain Rahi Pyar Ke",
        artist: "Kishore Kumar & S. D. Burman",
        song_duration: "04:51",
        img: "Ham Hain Rahi Pyar Ke",
        src: "Ham Hain Rahi Pyar Ke",
    },
    
    {
        name: "Har Dil Jo Pyar Karega",
        artist: "Lata Mangeshkar & Mukesh & Mahendra Kapoor",
        song_duration: "04:46",
        img: "Har Dil Jo Pyar Karega",
        src: "Har Dil Jo Pyar Karega",
    },
    {
        name: "Haye Haye Yeh Majboori",
        artist: "Lata Mangeshkar & Laxmikant–Pyarelal",
        song_duration: "04:16",
        img: "Haye Haye Yeh Majboori",
        src: "Haye Haye Yeh Majboori",
    },
    {
        name: "Hazaar Rahen Mud Ke Dekhin",
        artist: "Lata Mangeshkar & Kishore Kumar",
        song_duration: "05:18",
        img: "Hazaar Rahen Mud Ke Dekhin",
        src: "Hazaar Rahen Mud Ke Dekhin",
    },
    {
        name: "Ho Gaya Hai Tujhko To Pyar Sajna",
        artist: "Lata Mangeshkar & Udit Narayan",
        song_duration: "05:49",
        img: "Ho Gaya Hai Tujhko To Pyar Sajna",
        src: "Ho Gaya Hai Tujhko To Pyar Sajna",
    },
    {
        name: "Ho Pardesia",
        artist: "Lata Mangeshkar & Kishore Kumar",
        song_duration: "04:52",
        img: "Ho Pardesia",
        src: "Ho Pardesia",
    },
    {
        name: "Hum Aap Ki Ankhon Mein",
        artist: "Geeta Dutt & Mohammed Rafi & S. D. Burman",
        song_duration: "03:53",
        img: "Hum Aap Ki Ankhon Mein",
        src: "Hum Aap Ki Ankhon Mein",
    },
    {
        name: "Hum Bekhudi Mein Tum Ko Pukare",
        artist: "Mohammed Rafi & S. D. Burman",
        song_duration: "03:25",
        img: "Hum Bekhudi Mein Tum Ko Pukare",
        src: "Hum Bekhudi Mein Tum Ko Pukare",
    },
    {
        name: "Hum Dono Do Premi",
        artist: "Lata Mangeshkar & Kishore Kumar & R. D. Burman",
        song_duration: "04:30",
        img: "Hum Dono Do Premi",
        src: "Hum Dono Do Premi",
    },
    {
        name: "Hum The Jinke Sahare",
        artist: "Lata Mangeshkar & Kalyanji-Anandji",
        song_duration: "03:51",
        img: "Hum The Jinke Sahare",
        src: "Hum The Jinke Sahare",
    },
    {
        name: "Humen Tumse Pyar Kitna",
        artist: "Parveen Sultana & R. D. Burman",
        song_duration: "04:53",
        img: "Humen Tumse Pyar Kitna",
        src: "Humen Tumse Pyar Kitna",
    },
    {
        name: "Hungama Ho Gaya",
        artist: "Asha Bhosle & Laxmikant–Pyarelal",
        song_duration: "05:20",
        img: "Hungama Ho Gaya",
        src: "Hungama Ho Gaya",
    },
    {
        name: "Husn Hazir Hain",
        artist: "Lata Mangeshkar",
        song_duration: "06:20",
        img: "Husn Hazir Hain",
        src: "Husn Hazir Hain",
    },
    {
        name: "Ik Rasta Hai Zindagi",
        artist: "Lata Mangeshkar & Kishore Kumar",
        song_duration: "05:17",
        img: "Ik Rasta Hai Zindagi",
        src: "Ik Rasta Hai Zindagi",
    },
    {
        name: "In Ankhon Ki Masti",
        artist: "Asha Bhosle",
        song_duration: "05:43",
        img: "In Ankhon Ki Masti",
        src: "In Ankhon Ki Masti",
    },
    {
        name: "Intaha Ho Gai Intezar Ki",
        artist: "Kishore Kumar & Asha Bhosle",
        song_duration: "08:49",
        img: "Intaha Ho Gai Intezar Ki",
        src: "Intaha Ho Gai Intezar Ki",
    },
    {
        name: "Is Mod Se Jate Hain",
        artist: "Lata Mangeshkar & Kishore Kumar & R. D. Burman",
        song_duration: "04:56",
        img: "Is Mod Se Jate Hain",
        src: "Is Mod Se Jate Hain",
    },
    {
        name: "Isharon Isharon Men Dil Lenewale",
        artist: "Asha Bhosle & Mohammed Rafi",
        song_duration: "04:50",
        img: "Isharon Isharon Men Dil Lenewale",
        src: "Isharon Isharon Men Dil Lenewale",
    },
    {
        name: "Itna To Yaad Hai Mujhe",
        artist: "Mohammed Rafi & Lata Mangeshkar & Laxmikant–Pyarelal",
        song_duration: "06:15",
        img: "Itna To Yaad Hai Mujhe",
        src: "Itna To Yaad Hai Mujhe",
    },
    
    {
        name: "Jaaneman Jaaneman Tere Do Nain",
        artist: "K. J. Yesudas & Asha Bhosle & Salil Chowdhury",
        song_duration: "05:05",
        img: "Jaaneman Jaaneman Tere Do Nain",
        src: "Jaaneman Jaaneman Tere Do Nain",
    },
    {
        name: "Jab Chhaye Mera Jadoo",
        artist: "Asha Bhosle",
        song_duration: "05:20",
        img: "Jab Chhaye Mera Jadoo",
        src: "Jab Chhaye Mera Jadoo",
    },
    {
        name: "Jab Hum Jawan Honge",
        artist: "Lata Mangeshkar & Shabbir Kumar & R. D. Burman",
        song_duration: "07:09",
        img: "Jab Hum Jawan Honge",
        src: "Jab Hum Jawan Honge",
    },
    {
        name: "Jai Jai Shiv Shankar",
        artist: "Lata Mangeshkar & Kishore Kumar & R. D. Burman",
        song_duration: "05:37",
        img: "Jai Jai Shiv Shankar",
        src: "Jai Jai Shiv Shankar",
    },
    {
        name: "Jaiye Aap Kahan Jayenge - Asha Bhosle",
        artist: "Asha Bhosle",
        song_duration: "06:23",
        img: "Jaiye Aap Kahan Jayenge - Asha Bhosle",
        src: "Jaiye Aap Kahan Jayenge - Asha Bhosle",
    },
    {
        name: "Jane Kahan Gaye Woh Din",
        artist: "Mukesh",
        song_duration: "03:38",
        img: "Jane Kahan Gaye Woh Din",
        src: "Jane Kahan Gaye Woh Din",
    },
    {
        name: "Jane Kyon Log Mohabbat Kiya",
        artist: "Lata Mangeshkar & Laxmikant–Pyarelal",
        song_duration: "04:59",
        img: "Jane Kyon Log Mohabbat Kiya",
        src: "Jane Kyon Log Mohabbat Kiya",
    },
    {
        name: "Janeman Tum Kamal Karte Ho",
        artist: "Lata Mangeshkar & Kishore Kumar",
        song_duration: "05:40",
        img: "Janeman Tum Kamal Karte Ho",
        src: "Janeman Tum Kamal Karte Ho",
    },
    {
        name: "Jawani Jan-E-Man",
        artist: "Asha Bhosle",
        song_duration: "05:36",
        img: "Jawani Jan-E-Man",
        src: "Jawani Jan-E-Man",
    },
    {
        name: "Jeena Yahan Marna Yahan - With Dialogue",
        artist: "Mukesh",
        song_duration: "04:28",
        img: "Jeena Yahan Marna Yahan - With Dialogue",
        src: "Jeena Yahan Marna Yahan - With Dialogue",
    },
    {
        name: "Jeevan Ke Din",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "05:03",
        img: "Jeevan Ke Din",
        src: "Jeevan Ke Din",
    },
    {
        name: "Jeevan Se Bhari Teri Ankhen",
        artist: "Kishore Kumar & Kalyanji-Anandji",
        song_duration: "03:26",
        img: "Jeevan Se Bhari Teri Ankhen",
        src: "Jeevan Se Bhari Teri Ankhen",
    },
    {
        name: "Jhilmil Sitaron Ka Angan Hoga",
        artist: "Lata Mangeshkar & Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "05:28",
        img: "Jhilmil Sitaron Ka Angan Hoga",
        src: "Jhilmil Sitaron Ka Angan Hoga",
    },
    {
        name: "Jis Gali Mein Tera Ghar",
        artist: "Mukesh & R. D. Burman",
        song_duration: "04:01",
        img: "Jis Gali Mein Tera Ghar",
        src: "Jis Gali Mein Tera Ghar",
    },
    {
        name: "Jo Tumko Hopasand Wohi Baat Karenge",
        artist: "Mukesh & Kalyanji-Anandji",
        song_duration: "04:41",
        img: "Jo Tumko Hopasand Wohi Baat Karenge",
        src: "Jo Tumko Hopasand Wohi Baat Karenge",
    },
    {
        name: "Jo Wada Kiya Woh Nibhana Padega - Happy",
        artist: "Mohammed Rafi & Lata Mangeshkar",
        song_duration: "03:15",
        img: "Jo Wada Kiya Woh Nibhana Padega - Happy",
        src: "Jo Wada Kiya Woh Nibhana Padega - Happy",
    },
    {
        name: "Kab Ke Bichhde Hue",
        artist: "Asha Bhosle & Kishore Kumar & Kalyanji-Anandji",
        song_duration: "06:12",
        img: "Kab Ke Bichhde Hue",
        src: "Kab Ke Bichhde Hue",
    },
    {
        name: "Kabhi Kabhi Mere Dil Mein Duet",
        artist: "Mukesh & Lata Mangeshkar",
        song_duration: "04:58",
        img: "Kabhi Kabhi Mere Dil Mein Duet",
        src: "Kabhi Kabhi Mere Dil Mein Duet",
    },
    {
        name: "Kabhi Main Kahoon",
        artist: "Lata Mangeshkar & Hariharan",
        song_duration: "07:24",
        img: "Kabhi Main Kahoon",
        src: "Kabhi Main Kahoon",
    },
    {
        name: "Kahin Door Jab Din Dhal Jaye",
        artist: "Mukesh & Salil Chowdhury",
        song_duration: "05:37",
        img: "Kahin Door Jab Din Dhal Jaye",
        src: "Kahin Door Jab Din Dhal Jaye",
    },
    
    {
        name: "Kajra Mohabbat Wala",
        artist: "Asha Bhosle & Shamshad Begum",
        song_duration: "06:13",
        img: "Kajra Mohabbat Wala",
        src: "Kajra Mohabbat Wala",
    },
    {
        name: "Kanchi Re Kanchi Re",
        artist: "Lata Mangeshkar & Kishore Kumar & R. D. Burman",
        song_duration: "04:57",
        img: "Kanchi Re Kanchi Re",
        src: "Kanchi Re Kanchi Re",
    },
    {
        name: "Karvaten Badalte Rahe",
        artist: "Kishore Kumar & Lata Mangeshkar & R. D. Burman",
        song_duration: "05:10",
        img: "Karvaten Badalte Rahe",
        src: "Karvaten Badalte Rahe",
    },
    {
        name: "Katra Katra",
        artist: "Asha Bhosle & R. D. Burman",
        song_duration: "06:03",
        img: "Katra Katra",
        src: "Katra Katra",
    },
    {
        name: "Kehna Hai Kehna Hai",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "03:41",
        img: "Kehna Hai Kehna Hai",
        src: "Kehna Hai Kehna Hai",
    },
    {
        name: "Khaike Paan Banaras Wala",
        artist: "Kishore Kumar & Kalyanji-Anandji",
        song_duration: "03:57",
        img: "Khaike Paan Banaras Wala",
        src: "Khaike Paan Banaras Wala",
    },
    {
        name: "Khali Hath Sham Aai Hai",
        artist: "Asha Bhosle & R. D. Burman",
        song_duration: "05:00",
        img: "Khali Hath Sham Aai Hai",
        src: "Khali Hath Sham Aai Hai",
    },
    {
        name: "Khilte Hain Gul Yahan",
        artist: "Kishore Kumar",
        song_duration: "04:02",
        img: "Khilte Hain Gul Yahan",
        src: "Khilte Hain Gul Yahan",
    },
    {
        name: "Khoya Khoya Chand Khula Aasman",
        artist: "Mohammed Rafi & S. D. Burman",
        song_duration: "04:40",
        img: "Khoya Khoya Chand Khula Aasman",
        src: "Khoya Khoya Chand Khula Aasman",
    },
    {
        name: "Khullam Khulla Pyar Karenge",
        artist: "Asha Bhosle & Kishore Kumar & R. D. Burman",
        song_duration: "05:16",
        img: "Khullam Khulla Pyar Karenge",
        src: "Khullam Khulla Pyar Karenge",
    },
    {
        name: "Khwab Ho Tum Ya Koi Haqeeqat",
        artist: "Kishore Kumar & S. D. Burman",
        song_duration: "05:33",
        img: "Khwab Ho Tum Ya Koi Haqeeqat",
        src: "Khwab Ho Tum Ya Koi Haqeeqat",
    },
    {
        name: "Kisi Ki Muskurahaton Pe Jhankar Beats",
        artist: "Hero And King Of Jhankar Studio & Mukesh",
        song_duration: "04:20",
        img: "Kisi Ki Muskurahaton Pe Jhankar Beats",
        src: "Kisi Ki Muskurahaton Pe Jhankar Beats",
    },
    {
        name: "Kitna Pyara Wada Hai",
        artist: "Lata Mangeshkar & Mohammed Rafi & R. D. Burman",
        song_duration: "05:13",
        img: "Kitna Pyara Wada Hai",
        src: "Kitna Pyara Wada Hai",
    },
    {
        name: "Koi Hamdam Na Raha",
        artist: "Kishore Kumar",
        song_duration: "03:24",
        img: "Koi Hamdam Na Raha",
        src: "Koi Hamdam Na Raha",
    },
    {
        name: "Koi Hota Jisko Apna",
        artist: "Kishore Kumar & Salil Chowdhury",
        song_duration: "03:28",
        img: "Koi Hota Jisko Apna",
        src: "Koi Hota Jisko Apna",
    },
    {
        name: "Koi Shahri Babu",
        artist: "Asha Bhosle & Laxmikant–Pyarelal",
        song_duration: "04:33",
        img: "Koi Shahri Babu",
        src: "Koi Shahri Babu",
    },
    {
        name: "Kora Kagaz Tha Yeh Man Mera",
        artist: "Lata Mangeshkar & Kishore Kumar & S. D. Burman",
        song_duration: "05:38",
        img: "Kora Kagaz Tha Yeh Man Mera",
        src: "Kora Kagaz Tha Yeh Man Mera",
    },
    {
        name: "Kuchh To Log Kahenge",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:19",
        img: "Kuchh To Log Kahenge",
        src: "Kuchh To Log Kahenge",
    },
    {
        name: "Kya Ghazab Karte Ho Ji",
        artist: "Asha Bhosle & R. D. Burman",
        song_duration: "03:25",
        img: "Kya Ghazab Karte Ho Ji",
        src: "Kya Ghazab Karte Ho Ji",
    },
    {
        name: "Kya Hua Tera Vada",
        artist: "Sushma Shrestha & Mohammed Rafi & R. D. Burman",
        song_duration: "04:18",
        img: "Kya Hua Tera Vada",
        src: "Kya Hua Tera Vada",
    },
    {
        name: "Kya Khoob Lagti Ho",
        artist: "Mukesh & Kanchan & Kalyanji-Anandji",
        song_duration: "03:59",
        img: "Kya Khoob Lagti Ho",
        src: "Kya Khoob Lagti Ho",
    },
    {
        name: "Lag Ja Gale Se Phir",
        artist: "Lata Mangeshkar",
        song_duration: "04:17",
        img: "Lag Ja Gale Se Phir",
        src: "Lag Ja Gale Se Phir",
    },
    {
        name: "Lakhon Hain Nigahon Mein",
        artist: "Mohammed Rafi",
        song_duration: "04:18",
        img: "Lakhon Hain Nigahon Mein",
        src: "Lakhon Hain Nigahon Mein",
    },
    {
        name: "Lekar Hum Diwana Dil",
        artist: "Asha Bhosle & Kishore Kumar & R. D. Burman",
        song_duration: "05:57",
        img: "Lekar Hum Diwana Dil",
        src: "Lekar Hum Diwana Dil",
    },
    {
        name: "Leke Pahla Pahla Pyar",
        artist: "Shamshad Begum & Asha Bhosle & Mohammed Rafi",
        song_duration: "06:45",
        img: "Leke Pahla Pahla Pyar",
        src: "Leke Pahla Pahla Pyar",
    },
    {
        name: "Likha Hai Teri Ankhon Mein",
        artist: "Lata Mangeshkar & Kishore Kumar & S. D. Burman",
        song_duration: "04:15",
        img: "Likha Hai Teri Ankhon Mein",
        src: "Likha Hai Teri Ankhon Mein",
    },
    {
        name: "Likhe Jo Khat Tujhe",
        artist: "Mohammed Rafi",
        song_duration: "04:33",
        img: "Likhe Jo Khat Tujhe",
        src: "Likhe Jo Khat Tujhe",
    },
    {
        name: "Loote Koi Man Ka Nagar",
        artist: "Lata Mangeshkar & Manhar Udhas & S. D. Burman",
        song_duration: "03:34",
        img: "Loote Koi Man Ka Nagar",
        src: "Loote Koi Man Ka Nagar",
    },
    {
        name: "Main Hoon Jhoom Jhoom Jhumroo",
        artist: "Kishore Kumar",
        song_duration: "03:24",
        img: "Main Hoon Jhoom Jhoom Jhumroo",
        src: "Main Hoon Jhoom Jhoom Jhumroo",
    },
    {
        name: "Main Jat Yamla Pagla Diwana",
        artist: "Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "04:38",
        img: "Main Jat Yamla Pagla Diwana",
        src: "Main Jat Yamla Pagla Diwana",
    },
    {
        name: "Main Pal Do Pal Ka Shair Hoon",
        artist: "Mukesh",
        song_duration: "03:24",
        img: "Main Pal Do Pal Ka Shair Hoon",
        src: "Main Pal Do Pal Ka Shair Hoon",
    },
    {
        name: "Main Shair Badnaam",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "05:20",
        img: "Main Shair Badnaam",
        src: "Main Shair Badnaam",
    },
    {
        name: "Main Tere Ishq Mein",
        artist: "Lata Mangeshkar & Laxmikant–Pyarelal",
        song_duration: "04:46",
        img: "Main Tere Ishq Mein",
        src: "Main Tere Ishq Mein",
    },
    {
        name: "Main Zindagi Ka Saath Nibhata Chala Gaya",
        artist: "Mohammed Rafi",
        song_duration: "03:50",
        img: "Main Zindagi Ka Saath Nibhata Chala Gaya",
        src: "Main Zindagi Ka Saath Nibhata Chala Gaya",
    },
    {
        name: "Maine Kaha Phoolon Se",
        artist: "Lata Mangeshkar & S. D. Burman",
        song_duration: "05:01",
        img: "Maine Kaha Phoolon Se",
        src: "Maine Kaha Phoolon Se",
    },
    {
        name: "Maine Tere Liye",
        artist: "Mukesh & Salil Chowdhury",
        song_duration: "03:06",
        img: "Maine Tere Liye",
        src: "Maine Tere Liye",
    },
    {
        name: "Mana Janab Ne Pukara Nahin",
        artist: "Kishore Kumar & S. D. Burman",
        song_duration: "04:07",
        img: "Mana Janab Ne Pukara Nahin",
        src: "Mana Janab Ne Pukara Nahin",
    },
    {
        name: "Mang Ke Saath Tumhara",
        artist: "Mohammed Rafi & Asha Bhosle",
        song_duration: "03:38",
        img: "Mang Ke Saath Tumhara",
        src: "Mang Ke Saath Tumhara",
    },
    {
        name: "Manzilen Apni Jagah Hai",
        artist: "Kishore Kumar",
        song_duration: "05:52",
        img: "Manzilen Apni Jagah Hai",
        src: "Manzilen Apni Jagah Hai",
    },
    {
        name: "Mausam Hai Ashiqana",
        artist: "Lata Mangeshkar",
        song_duration: "04:53",
        img: "Mausam Hai Ashiqana",
        src: "Mausam Hai Ashiqana",
    },
    {
        name: "Mausam Ka Jaadu",
        artist: "Lata Mangeshkar & S. P. Balasubrahmanyam",
        song_duration: "05:03",
        img: "Mausam Ka Jaadu",
        src: "Mausam Ka Jaadu",
    },
    {
        name: "Mausam Pyar Ka",
        artist: "Asha Bhosle & Kishore Kumar & R. D. Burman",
        song_duration: "05:43",
        img: "Mausam Pyar Ka",
        src: "Mausam Pyar Ka",
    },
    {
        name: "Maye Ni Maye",
        artist: "Lata Mangeshkar",
        song_duration: "04:21",
        img: "Maye Ni Maye",
        src: "Maye Ni Maye",
    },
    {
        name: "Meet Na Mila Re Man Ka",
        artist: "Kishore Kumar & S. D. Burman",
        song_duration: "04:20",
        img: "Meet Na Mila Re Man Ka",
        src: "Meet Na Mila Re Man Ka",
    },
    
    {
        name: "Mehboob Mere Mehboob Mere",
        artist: "Lata Mangeshkar & Mukesh & Laxmikant–Pyarelal",
        song_duration: "04:48",
        img: "Mehboob Mere Mehboob Mere",
        src: "Mehboob Mere Mehboob Mere",
    },
    {
        name: "Mehndi Laga Ke Rakhna",
        artist: "Lata Mangeshkar & Udit Narayan",
        song_duration: "04:46",
        img: "Mehndi Laga Ke Rakhna",
        src: "Mehndi Laga Ke Rakhna",
    },
    {
        name: "Mera Jeevan Kora Kagaz",
        artist: "Kishore Kumar & Kalyanji-Anandji",
        song_duration: "03:35",
        img: "Mera Jeevan Kora Kagaz",
        src: "Mera Jeevan Kora Kagaz",
    },
    {
        name: "Mera Joota Hai Japani",
        artist: "Mukesh",
        song_duration: "04:28",
        img: "Mera Joota Hai Japani",
        src: "Mera Joota Hai Japani",
    },
    {
        name: "Mera Kuchh Samaan",
        artist: "Asha Bhosle & R. D. Burman",
        song_duration: "06:39",
        img: "Mera Kuchh Samaan",
        src: "Mera Kuchh Samaan",
    },
    {
        name: "Mera Saaya Saath Hoga",
        artist: "Lata Mangeshkar",
        song_duration: "06:03",
        img: "Mera Saaya Saath Hoga",
        src: "Mera Saaya Saath Hoga",
    },
    {
        name: "Mere Dil Mein Aaj Kya Hai",
        artist: "Kishore Kumar & Laxmikant–Pyarelal",
        song_duration: "04:16",
        img: "Mere Dil Mein Aaj Kya Hai",
        src: "Mere Dil Mein Aaj Kya Hai",
    },
    {
        name: "Mere Hathon Men Nau Nau Churiyan",
        artist: "Lata Mangeshkar",
        song_duration: "05:46",
        img: "Mere Hathon Men Nau Nau Churiyan",
        src: "Mere Hathon Men Nau Nau Churiyan",
    },
    {
        name: "Mere Khwabon Mein",
        artist: "Lata Mangeshkar",
        song_duration: "04:16",
        img: "Mere Khwabon Mein",
        src: "Mere Khwabon Mein",
    },
    {
        name: "Mere Mehboob Qayamat Hogi",
        artist: "Kishore Kumar & Laxmikant–Pyarelal",
        song_duration: "03:48",
        img: "Mere Mehboob Qayamat Hogi",
        src: "Mere Mehboob Qayamat Hogi",
    },
    {
        name: "Mere Naina Sawan Bhadon",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "05:25",
        img: "Mere Naina Sawan Bhadon",
        src: "Mere Naina Sawan Bhadon",
    },
    {
        name: "Mere Samnewali Khidki Mein",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "02:52",
        img: "Mere Samnewali Khidki Mein",
        src: "Mere Samnewali Khidki Mein",
    },
    {
        name: "Mere Sapnon Ki Rani",
        artist: "Kishore Kumar & S. D. Burman",
        song_duration: "05:00",
        img: "Mere Sapnon Ki Rani",
        src: "Mere Sapnon Ki Rani",
    },
    {
        name: "Meri Bheegi Bheegi Si",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:06",
        img: "Meri Bheegi Bheegi Si",
        src: "Meri Bheegi Bheegi Si",
    },
    {
        name: "Mil Gaya Humko Saathi Mil Gaya",
        artist: "Asha Bhosle & Kishore Kumar & R. D. Burman",
        song_duration: "03:52",
        img: "Mil Gaya Humko Saathi Mil Gaya",
        src: "Mil Gaya Humko Saathi Mil Gaya",
    },
    {
        name: "Milo Na Tum To Ham Ghabraye",
        artist: "Lata Mangeshkar",
        song_duration: "04:58",
        img: "Milo Na Tum To Ham Ghabraye",
        src: "Milo Na Tum To Ham Ghabraye",
    },
    {
        name: "Mohabbat Bade Kaam Ki Cheez Hai",
        artist: "Lata Mangeshkar & Kishore Kumar & K. J. Yesudas",
        song_duration: "03:26",
        img: "Mohabbat Bade Kaam Ki Cheez Hai",
        src: "Mohabbat Bade Kaam Ki Cheez Hai",
    },
    {
        name: "Mujhe Naulakha Mangawa De Re Full Verson",
        artist: "Asha Bhosle & Kishore Kumar",
        song_duration: "00:29",
        img: "Mujhe Naulakha Mangawa De Re Full Verson",
        src: "Mujhe Naulakha Mangawa De Re Full Verson",
    },
    {
        name: "Mujhe Teri Mohabbat Ka Sahara",
        artist: "Mohammed Rafi & Lata Mangeshkar & Laxmikant–Pyarelal",
        song_duration: "06:21",
        img: "Mujhe Teri Mohabbat Ka Sahara",
        src: "Mujhe Teri Mohabbat Ka Sahara",
    },
    {
        name: "Musafir Hoon Yaron",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "03:09",
        img: "Musafir Hoon Yaron",
        src: "Musafir Hoon Yaron",
    },
    {
        name: "Muskurata Hua",
        artist: "Kishore Kumar",
        song_duration: "06:51",
        img: "Muskurata Hua",
        src: "Muskurata Hua",
    },
    
    {
        name: "Na Bole Tum Na Maine Kuchh Kaha",
        artist: "Asha Bhosle & Amit Kumar",
        song_duration: "03:31",
        img: "Na Bole Tum Na Maine Kuchh Kaha",
        src: "Na Bole Tum Na Maine Kuchh Kaha",
    },
    {
        name: "Na Ja Kahin Ab Na Ja - Mohdrafi",
        artist: "Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "06:27",
        img: "Na Ja Kahin Ab Na Ja - Mohdrafi",
        src: "Na Ja Kahin Ab Na Ja - Mohdrafi",
    },
    {
        name: "Na Jane Kyon Hota Hai",
        artist: "Lata Mangeshkar & Salil Chowdhury",
        song_duration: "03:12",
        img: "Na Jane Kyon Hota Hai",
        src: "Na Jane Kyon Hota Hai",
    },
    {
        name: "Na Jiya Lage Na",
        artist: "Lata Mangeshkar & Salil Chowdhury",
        song_duration: "03:22",
        img: "Na Jiya Lage Na",
        src: "Na Jiya Lage Na",
    },
    {
        name: "Naam Goom Jayega",
        artist: "Lata Mangeshkar & Bhupinder Singh & R. D. Burman",
        song_duration: "05:12",
        img: "Naam Goom Jayega",
        src: "Naam Goom Jayega",
    },
    {
        name: "Nazrana Bheja Kisi Ne Pyar Ka",
        artist: "Kishore Kumar",
        song_duration: "04:22",
        img: "Nazrana Bheja Kisi Ne Pyar Ka",
        src: "Nazrana Bheja Kisi Ne Pyar Ka",
    },
    {
        name: "Neela Aasman So Gaya - Amitabh Bachchan",
        artist: "Amitabh Bachchan",
        song_duration: "04:34",
        img: "Neela Aasman So Gaya - Amitabh Bachchan",
        src: "Neela Aasman So Gaya - Amitabh Bachchan",
    },
    {
        name: "O Haseena Zulfonwale Jane Jahan",
        artist: "Asha Bhosle & Mohammed Rafi & R. D. Burman",
        song_duration: "06:55",
        img: "O Haseena Zulfonwale Jane Jahan",
        src: "O Haseena Zulfonwale Jane Jahan",
    },
    {
        name: "O Majhi Re Apna Kinara",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "03:04",
        img: "O Majhi Re Apna Kinara",
        src: "O Majhi Re Apna Kinara",
    },
    {
        name: "O Mere Dil Ke Chain",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:33",
        img: "O Mere Dil Ke Chain",
        src: "O Mere Dil Ke Chain",
    },
    {
        name: "O Mere Sona Re Sona",
        artist: "Asha Bhosle & Mohammed Rafi & R. D. Burman",
        song_duration: "05:00",
        img: "O Mere Sona Re Sona",
        src: "O Mere Sona Re Sona",
    },
    {
        name: "O Meri Sharmilee",
        artist: "Kishore Kumar",
        song_duration: "03:58",
        img: "O Meri Sharmilee",
        src: "O Meri Sharmilee",
    },
    {
        name: "O Meri Soni Meri Tamanna",
        artist: "Asha Bhosle & Kishore Kumar & R. D. Burman",
        song_duration: "04:30",
        img: "O Meri Soni Meri Tamanna",
        src: "O Meri Soni Meri Tamanna",
    },
    {
        name: "O Saathi Re - Kishore Kumar",
        artist: "Kishore Kumar & Kalyanji-Anandji",
        song_duration: "04:29",
        img: "O Saathi Re - Kishore Kumar",
        src: "O Saathi Re - Kishore Kumar",
    },
    {
        name: "O Sathi Chal",
        artist: "Asha Bhosle & Kishore Kumar & R. D. Burman",
        song_duration: "04:31",
        img: "O Sathi Chal",
        src: "O Sathi Chal",
    },
    {
        name: "Oh Hansini",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "05:24",
        img: "Oh Hansini",
        src: "Oh Hansini",
    },
    {
        name: "Om Shanti Om - Meri Umar Ke Naujawano",
        artist: "Kishore Kumar & Laxmikant–Pyarelal",
        song_duration: "08:50",
        img: "Om Shanti Om - Meri Umar Ke Naujawano",
        src: "Om Shanti Om - Meri Umar Ke Naujawano",
    },
    {
        name: "Pag Ghunghroo Baandh",
        artist: "Kishore Kumar",
        song_duration: "08:00",
        img: "Pag Ghunghroo Baandh",
        src: "Pag Ghunghroo Baandh",
    },
    
    {
        name: "Pahle Pahle Pyar Ki Mulaqaten",
        artist: "Kishore Kumar & Asha Bhosle & R. D. Burman",
        song_duration: "04:38",
        img: "Pahle Pahle Pyar Ki Mulaqaten",
        src: "Pahle Pahle Pyar Ki Mulaqaten",
    },
    {
        name: "Panna Ki Tamanna Hai",
        artist: "Kishore Kumar & Lata Mangeshkar & R. D. Burman",
        song_duration: "05:47",
        img: "Panna Ki Tamanna Hai",
        src: "Panna Ki Tamanna Hai",
    },
    {
        name: "Pardesiyon Se Na Ankhiyan Milana - Happy",
        artist: "Mohammed Rafi & Kalyanji-Anandji",
        song_duration: "03:20",
        img: "Pardesiyon Se Na Ankhiyan Milana - Happy",
        src: "Pardesiyon Se Na Ankhiyan Milana - Happy",
    },
    {
        name: "Patthar Ke Sanam",
        artist: "Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "04:57",
        img: "Patthar Ke Sanam",
        src: "Patthar Ke Sanam",
    },
    {
        name: "Phir Chiddi Raat",
        artist: "Lata Mangeshkar & Talat Aziz",
        song_duration: "05:07",
        img: "Phir Chiddi Raat",
        src: "Phir Chiddi Raat",
    },
    {
        name: "Phir Wohi Raat Hai Khwab Ki",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:26",
        img: "Phir Wohi Raat Hai Khwab Ki",
        src: "Phir Wohi Raat Hai Khwab Ki",
    },
    {
        name: "Phool Tumhe Bheja Hai Khat Mein",
        artist: "Lata Mangeshkar & Mukesh & Kalyanji-Anandji",
        song_duration: "04:46",
        img: "Phool Tumhe Bheja Hai Khat Mein",
        src: "Phool Tumhe Bheja Hai Khat Mein",
    },
    {
        name: "Phoolon Ke Rang Se",
        artist: "Kishore Kumar",
        song_duration: "05:06",
        img: "Phoolon Ke Rang Se",
        src: "Phoolon Ke Rang Se",
    },
    {
        name: "Piya Bina Piya Bina",
        artist: "Lata Mangeshkar & S. D. Burman",
        song_duration: "04:12",
        img: "Piya Bina Piya Bina",
        src: "Piya Bina Piya Bina",
    },
    {
        name: "Piya Tose Naina Laage Re",
        artist: "Lata Mangeshkar & S. D. Burman",
        song_duration: "08:29",
        img: "Piya Tose Naina Laage Re",
        src: "Piya Tose Naina Laage Re",
    },
    {
        name: "Piya Tu Ab To Aaja",
        artist: "Asha Bhosle & R. D. Burman",
        song_duration: "05:24",
        img: "Piya Tu Ab To Aaja",
        src: "Piya Tu Ab To Aaja",
    },
    {
        name: "Pukarta Chala Hoon Main",
        artist: "Mohammed Rafi",
        song_duration: "03:51",
        img: "Pukarta Chala Hoon Main",
        src: "Pukarta Chala Hoon Main",
    },
    {
        name: "Pyar Diwana Hota Hai",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:44",
        img: "Pyar Diwana Hota Hai",
        src: "Pyar Diwana Hota Hai",
    },
    {
        name: "Pyar Hua Iqrar Hua",
        artist: "Manna Dey & Lata Mangeshkar",
        song_duration: "04:20",
        img: "Pyar Hua Iqrar Hua",
        src: "Pyar Hua Iqrar Hua",
    },
    {
        name: "Pyar Ka Dard Hai",
        artist: "Kishore Kumar & Asha Bhosle",
        song_duration: "05:17",
        img: "Pyar Ka Dard Hai",
        src: "Pyar Ka Dard Hai",
    },
    {
        name: "Pyar Karne Wale",
        artist: "Lata Mangeshkar & Manhar Udhas & Laxmikant–Pyarelal",
        song_duration: "05:55",
        img: "Pyar Karne Wale",
        src: "Pyar Karne Wale",
    },
    {
        name: "Pyar Kiya To Darna Kya",
        artist: "Lata Mangeshkar",
        song_duration: "06:21",
        img: "Pyar Kiya To Darna Kya",
        src: "Pyar Kiya To Darna Kya",
    },
    {
        name: "Pyar Zindagi Hai",
        artist: "Lata Mangeshkar & Asha Bhosle & Mahendra Kapoor & Kalyanji-Anandji",
        song_duration: "07:25",
        img: "Pyar Zindagi Hai",
        src: "Pyar Zindagi Hai",
    },
    {
        name: "Raat Akeli Hai Bujh Gaye Die",
        artist: "Asha Bhosle & S. D. Burman",
        song_duration: "05:17",
        img: "Raat Akeli Hai Bujh Gaye Die",
        src: "Raat Akeli Hai Bujh Gaye Die",
    },
    {
        name: "Raat Baaqi Baat Baaqi",
        artist: "Shashi Kapoor & Asha Bhosle & Bappi Lahiri",
        song_duration: "06:19",
        img: "Raat Baaqi Baat Baaqi",
        src: "Raat Baaqi Baat Baaqi",
    },
    {
        name: "Raat Kali Ek Khwab Men Aai",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:59",
        img: "Raat Kali Ek Khwab Men Aai",
        src: "Raat Kali Ek Khwab Men Aai",
    },
    {
        name: "Raat Ke Hamsafar",
        artist: "Asha Bhosle & Mohammed Rafi",
        song_duration: "05:35",
        img: "Raat Ke Hamsafar",
        src: "Raat Ke Hamsafar",
    },
    {
        name: "Raina Beeti Jaye",
        artist: "Lata Mangeshkar & R. D. Burman",
        song_duration: "03:26",
        img: "Raina Beeti Jaye",
        src: "Raina Beeti Jaye",
    },
    {
        name: "Rajnigandha Phool Tumhare",
        artist: "Lata Mangeshkar & Salil Chowdhury",
        song_duration: "03:24",
        img: "Rajnigandha Phool Tumhare",
        src: "Rajnigandha Phool Tumhare",
    },
    {
        name: "Ramaiya Vastavaiya",
        artist: "Lata Mangeshkar & Mohammed Rafi & Mukesh",
        song_duration: "06:00",
        img: "Ramaiya Vastavaiya",
        src: "Ramaiya Vastavaiya",
    },
    {
        name: "Rangeela Re",
        artist: "Lata Mangeshkar",
        song_duration: "06:17",
        img: "Rangeela Re",
        src: "Rangeela Re",
    },
    {
        name: "Rim Jhim Ke Geet",
        artist: "Lata Mangeshkar & Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "04:39",
        img: "Rim Jhim Ke Geet",
        src: "Rim Jhim Ke Geet",
    },
    {
        name: "Rimjhim Gire Sawan",
        artist: "Kishore Kumar & Lata Mangeshkar & R. D. Burman",
        song_duration: "03:36",
        img: "Rimjhim Gire Sawan",
        src: "Rimjhim Gire Sawan",
    },
    {
        name: "Roop Tera Mastana",
        artist: "Kishore Kumar & S. D. Burman",
        song_duration: "03:45",
        img: "Roop Tera Mastana",
        src: "Roop Tera Mastana",
    },
    {
        name: "Rote Hue Aate Hain Sab",
        artist: "Kishore Kumar",
        song_duration: "04:55",
        img: "Rote Hue Aate Hain Sab",
        src: "Rote Hue Aate Hain Sab",
    },
    {
        name: "Roz Sham Aati Hai Magar Aesi",
        artist: "Lata Mangeshkar & Laxmikant–Pyarelal",
        song_duration: "03:11",
        img: "Roz Sham Aati Hai Magar Aesi",
        src: "Roz Sham Aati Hai Magar Aesi",
    },
    {
        name: "Ruk Jana Nahin- Pt. 1",
        artist: "Kishore Kumar & Laxmikant–Pyarelal",
        song_duration: "06:30",
        img: "Ruk Jana Nahin- Pt-1",
        src: "Ruk Jana Nahin- Pt-1",
    },
    {
        name: "Ruk Jana O Janan",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "03:40",
        img: "Ruk Jana O Janan",
        src: "Ruk Jana O Janan",
    },
    {
        name: "Sajna Hai Mujhe Sajna Ke Liye",
        artist: "Asha Bhosle",
        song_duration: "05:04",
        img: "Sajna Hai Mujhe Sajna Ke Liye",
        src: "Sajna Hai Mujhe Sajna Ke Liye",
    },
    {
        name: "Salame-Ishq Meri Jaan",
        artist: "Lata Mangeshkar & Kishore Kumar & Kalyanji-Anandji",
        song_duration: "05:50",
        img: "Salame-Ishq Meri Jaan",
        src: "Salame-Ishq Meri Jaan",
    },
    {
        name: "Sama Hai Suhana Suhana",
        artist: "Kishore Kumar & Kalyanji-Anandji",
        song_duration: "03:26",
        img: "Sama Hai Suhana Suhana",
        src: "Sama Hai Suhana Suhana",
    },
    {
        name: "Sawan Ka Mahina",
        artist: "Lata Mangeshkar & Mukesh & Laxmikant–Pyarelal",
        song_duration: "05:28",
        img: "Sawan Ka Mahina",
        src: "Sawan Ka Mahina",
    },
    {
        name: "Sheesha Ho Ya Dil Ho",
        artist: "Lata Mangeshkar & Laxmikant–Pyarelal",
        song_duration: "05:46",
        img: "Sheesha Ho Ya Dil Ho",
        src: "Sheesha Ho Ya Dil Ho",
    },
    {
        name: "Shokhiyon Mein Ghola Jaye",
        artist: "Lata Mangeshkar & Kishore Kumar",
        song_duration: "05:04",
        img: "Shokhiyon Mein Ghola Jaye",
        src: "Shokhiyon Mein Ghola Jaye",
    },
    
    {
        name: "Silli Hawa Chhoo Gai",
        artist: "Lata Mangeshkar & R. D. Burman",
        song_duration: "05:36",
        img: "Silli Hawa Chhoo Gai",
        src: "Silli Hawa Chhoo Gai",
    },
    {
        name: "Suhani Raat Dhal Chuki",
        artist: "Mohammed Rafi",
        song_duration: "03:29",
        img: "Suhani Raat Dhal Chuki",
        src: "Suhani Raat Dhal Chuki",
    },
    {
        name: "Sun Sahiba Sun",
        artist: "Lata Mangeshkar",
        song_duration: "05:14",
        img: "Sun Sahiba Sun",
        src: "Sun Sahiba Sun",
    },
    {
        name: "Suniye Kahiye Kahiye",
        artist: "Kishore Kumar & Asha Bhosle",
        song_duration: "05:05",
        img: "Suniye Kahiye Kahiye",
        src: "Suniye Kahiye Kahiye",
    },
    {
        name: "Suno Kaho Suna",
        artist: "Lata Mangeshkar & Kishore Kumar & R. D. Burman",
        song_duration: "04:20",
        img: "Suno Kaho Suna",
        src: "Suno Kaho Suna",
    },
    {
        name: "Taarif Karoon Kya Uski",
        artist: "Mohammed Rafi",
        song_duration: "05:26",
        img: "Taarif Karoon Kya Uski",
        src: "Taarif Karoon Kya Uski",
    },
    {
        name: "Tere Bina Jiya Jaye Naa",
        artist: "Lata Mangeshkar & R. D. Burman",
        song_duration: "05:46",
        img: "Tere Bina Jiya Jaye Naa",
        src: "Tere Bina Jiya Jaye Naa",
    },
    {
        name: "Tere Bina Zindagi Se",
        artist: "Lata Mangeshkar & Kishore Kumar & R. D. Burman",
        song_duration: "05:54",
        img: "Tere Bina Zindagi Se",
        src: "Tere Bina Zindagi Se",
    },
    {
        name: "Tere Chehre Mein Woh Jadoo Hai",
        artist: "Kishore Kumar & Kalyanji-Anandji",
        song_duration: "04:10",
        img: "Tere Chehre Mein Woh Jadoo Hai",
        src: "Tere Chehre Mein Woh Jadoo Hai",
    },
    {
        name: "Tere Chehre Se Nazar Nahin",
        artist: "Lata Mangeshkar & Kishore Kumar",
        song_duration: "05:02",
        img: "Tere Chehre Se Nazar Nahin",
        src: "Tere Chehre Se Nazar Nahin",
    },
    {
        name: "Tere Ghar Ke Samne",
        artist: "Lata Mangeshkar & Mohammed Rafi & S. D. Burman",
        song_duration: "03:30",
        img: "Tere Ghar Ke Samne",
        src: "Tere Ghar Ke Samne",
    },
    {
        name: "Tere Mere Milan Ki Yeh Raina",
        artist: "Lata Mangeshkar & Kishore Kumar & S. D. Burman",
        song_duration: "04:54",
        img: "Tere Mere Milan Ki Yeh Raina",
        src: "Tere Mere Milan Ki Yeh Raina",
    },
    {
        name: "Tere Mere Sapne Ab Ek Rang Hain",
        artist: "Mohammed Rafi & S. D. Burman",
        song_duration: "04:21",
        img: "Tere Mere Sapne Ab Ek Rang Hain",
        src: "Tere Mere Sapne Ab Ek Rang Hain",
    },
    {
        name: "Teri Aankhon Ke Siva",
        artist: "Mohammed Rafi",
        song_duration: "04:10",
        img: "Teri Aankhon Ke Siva",
        src: "Teri Aankhon Ke Siva",
    },
    {
        name: "Teri Bindiya Re",
        artist: "Lata Mangeshkar & Mohammed Rafi & S. D. Burman",
        song_duration: "04:32",
        img: "Teri Bindiya Re",
        src: "Teri Bindiya Re",
    },
    {
        name: "Teri Galiyon Mein",
        artist: "Mohammed Rafi",
        song_duration: "04:43",
        img: "Teri Galiyon Mein",
        src: "Teri Galiyon Mein",
    },
    {
        name: "Thodisi Jo Pee Lee Hai",
        artist: "Kishore Kumar",
        song_duration: "06:51",
        img: "Thodisi Jo Pee Lee Hai",
        src: "Thodisi Jo Pee Lee Hai",
    },
    {
        name: "Tu Is Tarah Se Mere Zindagi Main",
        artist: "Mohammed Rafi",
        song_duration: "06:34",
        img: "Tu Is Tarah Se Mere Zindagi Main",
        src: "Tu Is Tarah Se Mere Zindagi Main",
    },
    {
        name: "Tu Kahan Ye Bata",
        artist: "Mohammed Rafi & S. D. Burman",
        song_duration: "03:27",
        img: "Tu Kahan Ye Bata",
        src: "Tu Kahan Ye Bata",
    },
    {
        name: "Tu Mere Samne",
        artist: "Lata Mangeshkar & Udit Narayan",
        song_duration: "06:06",
        img: "Tu Mere Samne",
        src: "Tu Mere Samne",
    },
    {
        name: "Tujh Sang Preet",
        artist: "Kishore Kumar & Lata Mangeshkar",
        song_duration: "05:35",
        img: "Tujh Sang Preet",
        src: "Tujh Sang Preet",
    },
    {
        name: "Tujhe Dekha To",
        artist: "Lata Mangeshkar & Kumar Sanu",
        song_duration: "05:04",
        img: "Tujhe Dekha To",
        src: "Tujhe Dekha To",
    },
    {
        name: "Tujhe Jeevan Ki Dor Se",
        artist: "Lata Mangeshkar & Mohammed Rafi",
        song_duration: "03:19",
        img: "Tujhe Jeevan Ki Dor Se",
        src: "Tujhe Jeevan Ki Dor Se",
    },
    {
        name: "Tujhse Naraz Nahin Zindagi - Lata Mangeshkar",
        artist: "Lata Mangeshkar & Gulzar & R. D. Burman",
        song_duration: "03:40",
        img: "Tujhse Naraz Nahin Zindagi - Lata Mangeshkar",
        src: "Tujhse Naraz Nahin Zindagi - Lata Mangeshkar",
    },
    {
        name: "Tum Aa Gaye Ho Noor Aa Gaya",
        artist: "Lata Mangeshkar & Kishore Kumar & R. D. Burman",
        song_duration: "04:12",
        img: "Tum Aa Gaye Ho Noor Aa Gaya",
        src: "Tum Aa Gaye Ho Noor Aa Gaya",
    },
    {
        name: "Tum Bin Jaoon Kahan",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "03:30",
        img: "Tum Bin Jaoon Kahan",
        src: "Tum Bin Jaoon Kahan",
    },
    {
        name: "Tum Jo Mil Gaye Ho",
        artist: "Mohammed Rafi",
        song_duration: "08:06",
        img: "Tum Jo Mil Gaye Ho",
        src: "Tum Jo Mil Gaye Ho",
    },
    {
        name: "Tum Mujhe Yun Bhula Na Paoge",
        artist: "Mohammed Rafi",
        song_duration: "04:34",
        img: "Tum Mujhe Yun Bhula Na Paoge",
        src: "Tum Mujhe Yun Bhula Na Paoge",
    },
    {
        name: "Tumne Mujhe Dekha Hokar Meherban",
        artist: "Mohammed Rafi & R. D. Burman",
        song_duration: "04:38",
        img: "Tumne Mujhe Dekha Hokar Meherban",
        src: "Tumne Mujhe Dekha Hokar Meherban",
    },
    {
        name: "Tumse Achha Kaun Hai - Knockwell Chill Trap Mix",
        artist: "Knockwell & Mohammed Rafi",
        song_duration: "02:30",
        img: "Tumse Achha Kaun Hai - Knockwell Chill Trap Mix",
        src: "Tumse Achha Kaun Hai - Knockwell Chill Trap Mix",
    },
    {
        name: "Tune O Rangeele",
        artist: "Lata Mangeshkar & R. D. Burman",
        song_duration: "03:32",
        img: "Tune O Rangeele",
        src: "Tune O Rangeele",
    },
    {
        name: "Uden Jab Jab Zulfen Teri",
        artist: "Mohammed Rafi & Asha Bhosle",
        song_duration: "04:55",
        img: "Uden Jab Jab Zulfen Teri",
        src: "Uden Jab Jab Zulfen Teri",
    },
    {
        name: "Unse Mili Nazar Ke Mere Hosh Ud Gai",
        artist: "Lata Mangeshkar",
        song_duration: "04:05",
        img: "Unse Mili Nazar Ke Mere Hosh Ud Gai",
        src: "Unse Mili Nazar Ke Mere Hosh Ud Gai",
    },
    {
        name: "Wada Kar Le Sajna",
        artist: "Lata Mangeshkar & Mohammed Rafi & Kalyanji-Anandji",
        song_duration: "04:47",
        img: "Wada Kar Le Sajna",
        src: "Wada Kar Le Sajna",
    },
    {
        name: "Wadiyan Mera Daman",
        artist: "Mohammed Rafi & R. D. Burman",
        song_duration: "03:36",
        img: "Wadiyan Mera Daman",
        src: "Wadiyan Mera Daman",
    },
    {
        name: "Woh Hai Zara Khafa Khafa",
        artist: "Lata Mangeshkar & Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "05:53",
        img: "Woh Hai Zara Khafa Khafa",
        src: "Woh Hai Zara Khafa Khafa",
    },
    {
        name: "Woh Jab Yaad Aaye",
        artist: "Lata Mangeshkar & Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "04:43",
        img: "Woh Jab Yaad Aaye",
        src: "Woh Jab Yaad Aaye",
    },
    {
        name: "Woh Sham Kuchh Ajeeb Thi",
        artist: "Kishore Kumar & Hemant Kumar",
        song_duration: "04:45",
        img: "Woh Sham Kuchh Ajeeb Thi",
        src: "Woh Sham Kuchh Ajeeb Thi",
    },
    {
        name: "Yaar Ki Khabar Mil Gai",
        artist: "Asha Bhosle & Kishore Kumar & Laxmikant–Pyarelal",
        song_duration: "08:27",
        img: "Yaar Ki Khabar Mil Gai",
        src: "Yaar Ki Khabar Mil Gai",
    },
    {
        name: "Yahoo Chahe Koi Mujhe Junglee Kahe",
        artist: "Mohammed Rafi",
        song_duration: "04:55",
        img: "Yahoo Chahe Koi Mujhe Junglee Kahe",
        src: "Yahoo Chahe Koi Mujhe Junglee Kahe",
    },
    {
        name: "Yara Seeli Seeli",
        artist: "Lata Mangeshkar",
        song_duration: "05:06",
        img: "Yara Seeli Seeli",
        src: "Yara Seeli Seeli",
    },
    {
        name: "Ye Dil Tum Bin Lagta Nahin",
        artist: "Lata Mangeshkar & Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "05:51",
        img: "Ye Dil Tum Bin Lagta Nahin",
        src: "Ye Dil Tum Bin Lagta Nahin",
    },
    {
        name: "Ye Jo Chilman Hai",
        artist: "Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "04:48",
        img: "Ye Jo Chilman Hai",
        src: "Ye Jo Chilman Hai",
    },
    {
        name: "Ye Ladka Hay Allah Kaisa Hai Diwana",
        artist: "Asha Bhosle & Mohammed Rafi & R. D. Burman",
        song_duration: "05:29",
        img: "Ye Ladka Hay Allah Kaisa Hai Diwana",
        src: "Ye Ladka Hay Allah Kaisa Hai Diwana",
    },
    {
        name: "Ye Samaa Samaa Hai Pyar Ka",
        artist: "Lata Mangeshkar & Kalyanji-Anandji",
        song_duration: "03:18",
        img: "Ye Samaa Samaa Hai Pyar Ka",
        src: "Ye Samaa Samaa Hai Pyar Ka",
    },
    {
        name: "Yeh Dil Na Hota Bechara",
        artist: "Kishore Kumar & S. D. Burman",
        song_duration: "04:19",
        img: "Yeh Dil Na Hota Bechara",
        src: "Yeh Dil Na Hota Bechara",
    },
    {
        name: "Yeh Duniya Yeh Mehfil",
        artist: "Mohammed Rafi",
        song_duration: "07:03",
        img: "Yeh Duniya Yeh Mehfil",
        src: "Yeh Duniya Yeh Mehfil",
    },
    {
        name: "Yeh Jo Mohabbat Hai",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:07",
        img: "Yeh Jo Mohabbat Hai",
        src: "Yeh Jo Mohabbat Hai",
    },
    {
        name: "Yeh Kahan Aa Gaye Hum",
        artist: "Lata Mangeshkar & Amitabh Bachchan",
        song_duration: "07:54",
        img: "Yeh Kahan Aa Gaye Hum",
        src: "Yeh Kahan Aa Gaye Hum",
    },
    {
        name: "Yeh Kya Hua",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:32",
        img: "Yeh Kya Hua",
        src: "Yeh Kya Hua",
    },
    {
        name: "Yeh Kya Jagah Hai Doston",
        artist: "Asha Bhosle",
        song_duration: "06:17",
        img: "Yeh Kya Jagah Hai Doston",
        src: "Yeh Kya Jagah Hai Doston",
    },
    {
        name: "Yeh Mera Dil Yaar Ka Diwana",
        artist: "Asha Bhosle & Kalyanji-Anandji",
        song_duration: "04:13",
        img: "Yeh Mera Dil Yaar Ka Diwana",
        src: "Yeh Mera Dil Yaar Ka Diwana",
    },
    {
        name: "Yeh Mera Diwanapan Hai",
        artist: "Mukesh",
        song_duration: "03:46",
        img: "Yeh Mera Diwanapan Hai",
        src: "Yeh Mera Diwanapan Hai",
    },
    {
        name: "Yeh Naina Yeh Kaajal",
        artist: "Kishore Kumar",
        song_duration: "05:50",
        img: "Yeh Naina Yeh Kaajal",
        src: "Yeh Naina Yeh Kaajal",
    },
    {
        name: "Yeh Raat Bheegi Bheegi",
        artist: "Manna Dey & Lata Mangeshkar",
        song_duration: "04:29",
        img: "Yeh Raat Bheegi Bheegi",
        src: "Yeh Raat Bheegi Bheegi",
    },
    {
        name: "Yeh Raat Yeh Chandni - Hemant Kumar",
        artist: "Hemant Kumar & S. D. Burman",
        song_duration: "04:56",
        img: "Yeh Raat Yeh Chandni - Hemant Kumar",
        src: "Yeh Raat Yeh Chandni - Hemant Kumar",
    },
    {
        name: "Yeh Raaten Yeh Mausam",
        artist: "Kishore Kumar & Asha Bhosle",
        song_duration: "03:21",
        img: "Yeh Raaten Yeh Mausam",
        src: "Yeh Raaten Yeh Mausam",
    },
    {
        name: "Yeh Reshmi Zulfen",
        artist: "Mohammed Rafi & Laxmikant–Pyarelal",
        song_duration: "05:20",
        img: "Yeh Reshmi Zulfen",
        src: "Yeh Reshmi Zulfen",
    },
    {
        name: "Yeh Sham Mastani",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "04:36",
        img: "Yeh Sham Mastani",
        src: "Yeh Sham Mastani",
    },
    {
        name: "Zara Sa Jhoom Loon Main",
        artist: "Asha Bhosle & Abhijeet",
        song_duration: "05:53",
        img: "Zara Sa Jhoom Loon Main",
        src: "Zara Sa Jhoom Loon Main",
    },
    {
        name: "Zindagi Ek Safar Hai Suhana - Kishore Kumar",
        artist: "Kishore Kumar",
        song_duration: "04:21",
        img: "Zindagi Ek Safar Hai Suhana - Kishore Kumar",
        src: "Zindagi Ek Safar Hai Suhana - Kishore Kumar",
    },
    {
        name: "Zindagi Ka Safar",
        artist: "Kishore Kumar & Kalyanji-Anandji",
        song_duration: "03:59",
        img: "Zindagi Ka Safar",
        src: "Zindagi Ka Safar",
    },
    {
        name: "Zindagi Ke Safar Mein",
        artist: "Kishore Kumar & R. D. Burman",
        song_duration: "06:38",
        img: "Zindagi Ke Safar Mein",
        src: "Zindagi Ke Safar Mein",
    },
    {
        name: "Zindagi Pyar Ka Geet Hai",
        artist: "Lata Mangeshkar",
        song_duration: "05:32",
        img: "Zindagi Pyar Ka Geet Hai",
        src: "Zindagi Pyar Ka Geet Hai",
    }
];